genesis:
  started: 2026-01-22T00:00:00Z
  last_activity: 2026-01-26T21:30:00Z

core:
  vocabulary:
    status: stable
    terms: [Session, Evaluation, Condition, Transport, Tool, JSON-RPC]
  ontology:
    status: stable
  invariants:
    status: stable

features:
  mcp-protocol:
    phase: stable
    vocabulary: stable
    contracts: stable
    scenarios: stable
    properties: not-started
    verification: not-started

  code-evaluator:
    phase: stable
    vocabulary: stable
    contracts: stable
    scenarios: stable
    properties: not-started
    verification: not-started

  session-management:
    phase: stable
    vocabulary: stable
    contracts: stable
    scenarios: stable
    properties: not-started
    verification: not-started

  error-handling:
    phase: stable
    vocabulary: stable
    contracts: stable
    scenarios: stable
    properties: not-started
    verification: not-started

  introspection:
    phase: stable
    description: "Phase A - Introspection tools including validate-syntax"
    vocabulary: stable
    contracts: stable
    scenarios: stable
    properties: not-started
    verification: not-started
    tools:
      - describe-symbol
      - apropos-search
      - who-calls
      - who-references
      - macroexpand-form
      - validate-syntax (new - syntax validation without evaluation)

  enhanced-evaluation:
    phase: stable
    description: "Phase B - Enhanced evaluation with timing, compilation, and profiling"
    vocabulary: stable
    contracts: stable
    scenarios: not-started
    properties: not-started
    verification: not-started
    tools:
      - evaluate-lisp (enhanced with package, capture-time)
      - compile-form (new)
      - time-execution (new)

  error-intelligence:
    phase: stable
    description: "Phase C - Structured error capture with backtrace and restart info"
    vocabulary: stable
    contracts: stable
    scenarios: stable
    properties: not-started
    verification: not-started
    tools:
      - describe-last-error (new - get detailed info about most recent error)
      - get-backtrace (new - get stack trace from last error)

  clos-intelligence:
    phase: stable
    description: "Phase D - CLOS class and method introspection"
    vocabulary: stable
    contracts: stable
    scenarios: stable
    properties: not-started
    verification: not-started
    tools:
      - class-info (new - get comprehensive class information including slots)
      - find-methods (new - find all methods specialized on a class)
